[package]
name = "clia-ntex-session"
version = "0.3.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Session for ntex web framework."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/clia/ntex-extras.git"
documentation = "https://docs.rs/clia-ntex-session/"
license = "MIT"
edition = "2018"

[lib]
name = "clia_ntex_session"
path = "src/lib.rs"

[features]
default = ["cookie-session"]

# sessions feature, session require "ring" crate and c compiler
cookie-session = ["cookie/secure", "ntex/cookie"]

[dependencies]
ntex = "0.7.0"
cookie = "0.17"
derive_more = "0.99"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
time = { version = "0.3", default-features = false, features = ["std"] }

[dev-dependencies]
ntex = { version = "0.7.0", features=["tokio"] }
